#define WIFI_SSID "YOUR SSID"
#define WIFI_PASSWORD "YOUR WIFI PASSWORD"
#define THINGSPEAK_SERVER "api.thingspeak.com"
#define CHANNEL_ID YOUR CHANNEL ID
#define WRITE_APIKEY "XXXXXXXXXXXXX"
#define READ_APIKEY "XXXXXXXXXXXXX"